### ISSUE TITLE
Unhandled Exception when adding new account fails

### ISSUE THREAD

**Issue by charredgrass** [geel9/SteamAuth#3]
Geel, I'm reading through the code right now, and you are a visionary, I don't know how you even found these undocumented methods. I can sorta understand the code so if you get lazy and want someone to document the library, I can lend a hand.

Anyways, this happens when attempting to add a new account that fails because it already has mobile auth enabled on another account. It's after it asks me for an encryption key even though the login failed - which is probably the issue. Might want to catch that exception.

    ************** Exception Text **************
    System.ArgumentException: Password is empty
       at Steam_Desktop_Authenticator.FileEncryptor.DecryptData(String password, String passwordSalt, String IV, String encryptedData)
       at Steam_Desktop_Authenticator.Manifest.GetAllAccounts(String passKey)
       at Steam_Desktop_Authenticator.Manifest.VerifyPasskey(String passkey)
       at Steam_Desktop_Authenticator.MainForm.loadAccountsList()
       at Steam_Desktop_Authenticator.MainForm.btnSteamLogin_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by charredgrass** [comment]
Oh, I totally meant to submit this in the DesktopAuth repo. Disregard this issue...
